import fs from "node:fs/promises";
import { storageStatePath } from "./config";
import type { Browser, BrowserContext } from "@playwright/test";

import type { E2ERole } from "./config";

export const E2E_AUTH_TOKEN_STORAGE_KEY = "e2e_password_auth_token";
const PASSWORD_AUTH_TOKEN_STORAGE_KEY = "community_brief_password_auth_token";

function accessTokenFromState(state: any): string | null {
  for (const origin of state.origins ?? []) {
    const token = origin.localStorage?.find(
      (entry: { name?: string }) => entry.name === E2E_AUTH_TOKEN_STORAGE_KEY,
    )?.value;
    if (typeof token === "string" && token) return token;
  }
  return null;
}

export async function readE2EAccessToken(
  role: E2ERole,
): Promise<string | null> {
  try {
    const state = JSON.parse(await fs.readFile(storageStatePath(role), "utf8"));
    return accessTokenFromState(state);
  } catch {
    // Missing or stale state is regenerated by global setup.
  }
  return null;
}

export async function e2eAuthHeaders(
  role: E2ERole,
): Promise<Record<string, string>> {
  const token = await readE2EAccessToken(role);
  if (!token) throw new Error(`Missing E2E access token for role: ${role}`);
  return { Authorization: `Bearer ${token}` };
}

export async function addE2EAuthInitScript(
  context: BrowserContext,
): Promise<void> {
  const token = accessTokenFromState(await context.storageState());
  if (token) {
    await context.setExtraHTTPHeaders({ Authorization: `Bearer ${token}` });
  }
  await context.addInitScript(
    ({ sourceKey, targetKey }) => {
      const storedToken = window.localStorage.getItem(sourceKey);
      if (storedToken) window.sessionStorage.setItem(targetKey, storedToken);
    },
    {
      sourceKey: E2E_AUTH_TOKEN_STORAGE_KEY,
      targetKey: PASSWORD_AUTH_TOKEN_STORAGE_KEY,
    },
  );
}

export async function newE2EBrowserContext(
  browser: Browser,
  role: E2ERole,
): Promise<BrowserContext> {
  const context = await browser.newContext({
    storageState: storageStatePath(role),
    extraHTTPHeaders: await e2eAuthHeaders(role),
  });
  await addE2EAuthInitScript(context);
  return context;
}
