/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUnauthorisedIndexRouteImport } from './routes/_layout/unauthorised/index'
import { Route as LayoutSuggestTemplateIndexRouteImport } from './routes/_layout/suggest-template/index'
import { Route as LayoutSimpleUploadIndexRouteImport } from './routes/_layout/simple-upload/index'
import { Route as LayoutPromptManagementIndexRouteImport } from './routes/_layout/prompt-management/index'
import { Route as LayoutProfileIndexRouteImport } from './routes/_layout/profile/index'
import { Route as LayoutHelpIndexRouteImport } from './routes/_layout/help/index'
import { Route as LayoutAudioUploadIndexRouteImport } from './routes/_layout/audio-upload/index'
import { Route as LayoutAudioRecordingsIndexRouteImport } from './routes/_layout/audio-recordings/index'
import { Route as LayoutAnalyticsIndexRouteImport } from './routes/_layout/analytics/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutAudioRecordingsIdRouteImport } from './routes/_layout/audio-recordings/$id'
import { Route as LayoutAudioRecordingsSharedIndexRouteImport } from './routes/_layout/audio-recordings/shared/index'
import { Route as LayoutAdminUserManagementIndexRouteImport } from './routes/_layout/admin/user-management/index'
import { Route as LayoutAdminDeletedJobsIndexRouteImport } from './routes/_layout/admin/deleted-jobs/index'
import { Route as LayoutAdminAnnouncementsIndexRouteImport } from './routes/_layout/admin/announcements/index'
import { Route as LayoutAdminAllJobsIndexRouteImport } from './routes/_layout/admin/all-jobs/index'
import { Route as LayoutAdminUsersUserIdRouteImport } from './routes/_layout/admin/users/$userId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUnauthorisedIndexRoute = LayoutUnauthorisedIndexRouteImport.update({
  id: '/unauthorised/',
  path: '/unauthorised/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuggestTemplateIndexRoute =
  LayoutSuggestTemplateIndexRouteImport.update({
    id: '/suggest-template/',
    path: '/suggest-template/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSimpleUploadIndexRoute = LayoutSimpleUploadIndexRouteImport.update({
  id: '/simple-upload/',
  path: '/simple-upload/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPromptManagementIndexRoute =
  LayoutPromptManagementIndexRouteImport.update({
    id: '/prompt-management/',
    path: '/prompt-management/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/prompt-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHelpIndexRoute = LayoutHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAudioUploadIndexRoute = LayoutAudioUploadIndexRouteImport.update({
  id: '/audio-upload/',
  path: '/audio-upload/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAudioRecordingsIndexRoute =
  LayoutAudioRecordingsIndexRouteImport.update({
    id: '/audio-recordings/',
    path: '/audio-recordings/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAnalyticsIndexRoute = LayoutAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/analytics/index.lazy').then((d) => d.Route),
)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAudioRecordingsIdRoute = LayoutAudioRecordingsIdRouteImport.update({
  id: '/audio-recordings/$id',
  path: '/audio-recordings/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAudioRecordingsSharedIndexRoute =
  LayoutAudioRecordingsSharedIndexRouteImport.update({
    id: '/audio-recordings/shared/',
    path: '/audio-recordings/shared/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAdminUserManagementIndexRoute =
  LayoutAdminUserManagementIndexRouteImport.update({
    id: '/admin/user-management/',
    path: '/admin/user-management/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/admin/user-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LayoutAdminDeletedJobsIndexRoute =
  LayoutAdminDeletedJobsIndexRouteImport.update({
    id: '/admin/deleted-jobs/',
    path: '/admin/deleted-jobs/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/admin/deleted-jobs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LayoutAdminAnnouncementsIndexRoute =
  LayoutAdminAnnouncementsIndexRouteImport.update({
    id: '/admin/announcements/',
    path: '/admin/announcements/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/admin/announcements/index.lazy').then(
      (d) => d.Route,
    ),
  )
const LayoutAdminAllJobsIndexRoute = LayoutAdminAllJobsIndexRouteImport.update({
  id: '/admin/all-jobs/',
  path: '/admin/all-jobs/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/admin/all-jobs/index.lazy').then((d) => d.Route),
)
const LayoutAdminUsersUserIdRoute = LayoutAdminUsersUserIdRouteImport.update({
  id: '/admin/users/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/analytics/': typeof LayoutAnalyticsIndexRoute
  '/audio-recordings/': typeof LayoutAudioRecordingsIndexRoute
  '/audio-upload/': typeof LayoutAudioUploadIndexRoute
  '/help/': typeof LayoutHelpIndexRoute
  '/profile/': typeof LayoutProfileIndexRoute
  '/prompt-management/': typeof LayoutPromptManagementIndexRoute
  '/simple-upload/': typeof LayoutSimpleUploadIndexRoute
  '/suggest-template/': typeof LayoutSuggestTemplateIndexRoute
  '/unauthorised/': typeof LayoutUnauthorisedIndexRoute
  '/admin/users/$userId': typeof LayoutAdminUsersUserIdRoute
  '/admin/all-jobs/': typeof LayoutAdminAllJobsIndexRoute
  '/admin/announcements/': typeof LayoutAdminAnnouncementsIndexRoute
  '/admin/deleted-jobs/': typeof LayoutAdminDeletedJobsIndexRoute
  '/admin/user-management/': typeof LayoutAdminUserManagementIndexRoute
  '/audio-recordings/shared/': typeof LayoutAudioRecordingsSharedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/analytics': typeof LayoutAnalyticsIndexRoute
  '/audio-recordings': typeof LayoutAudioRecordingsIndexRoute
  '/audio-upload': typeof LayoutAudioUploadIndexRoute
  '/help': typeof LayoutHelpIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/prompt-management': typeof LayoutPromptManagementIndexRoute
  '/simple-upload': typeof LayoutSimpleUploadIndexRoute
  '/suggest-template': typeof LayoutSuggestTemplateIndexRoute
  '/unauthorised': typeof LayoutUnauthorisedIndexRoute
  '/admin/users/$userId': typeof LayoutAdminUsersUserIdRoute
  '/admin/all-jobs': typeof LayoutAdminAllJobsIndexRoute
  '/admin/announcements': typeof LayoutAdminAnnouncementsIndexRoute
  '/admin/deleted-jobs': typeof LayoutAdminDeletedJobsIndexRoute
  '/admin/user-management': typeof LayoutAdminUserManagementIndexRoute
  '/audio-recordings/shared': typeof LayoutAudioRecordingsSharedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_layout/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/analytics/': typeof LayoutAnalyticsIndexRoute
  '/_layout/audio-recordings/': typeof LayoutAudioRecordingsIndexRoute
  '/_layout/audio-upload/': typeof LayoutAudioUploadIndexRoute
  '/_layout/help/': typeof LayoutHelpIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/prompt-management/': typeof LayoutPromptManagementIndexRoute
  '/_layout/simple-upload/': typeof LayoutSimpleUploadIndexRoute
  '/_layout/suggest-template/': typeof LayoutSuggestTemplateIndexRoute
  '/_layout/unauthorised/': typeof LayoutUnauthorisedIndexRoute
  '/_layout/admin/users/$userId': typeof LayoutAdminUsersUserIdRoute
  '/_layout/admin/all-jobs/': typeof LayoutAdminAllJobsIndexRoute
  '/_layout/admin/announcements/': typeof LayoutAdminAnnouncementsIndexRoute
  '/_layout/admin/deleted-jobs/': typeof LayoutAdminDeletedJobsIndexRoute
  '/_layout/admin/user-management/': typeof LayoutAdminUserManagementIndexRoute
  '/_layout/audio-recordings/shared/': typeof LayoutAudioRecordingsSharedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/audio-recordings/$id'
    | '/admin/'
    | '/analytics/'
    | '/audio-recordings/'
    | '/audio-upload/'
    | '/help/'
    | '/profile/'
    | '/prompt-management/'
    | '/simple-upload/'
    | '/suggest-template/'
    | '/unauthorised/'
    | '/admin/users/$userId'
    | '/admin/all-jobs/'
    | '/admin/announcements/'
    | '/admin/deleted-jobs/'
    | '/admin/user-management/'
    | '/audio-recordings/shared/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/audio-recordings/$id'
    | '/admin'
    | '/analytics'
    | '/audio-recordings'
    | '/audio-upload'
    | '/help'
    | '/profile'
    | '/prompt-management'
    | '/simple-upload'
    | '/suggest-template'
    | '/unauthorised'
    | '/admin/users/$userId'
    | '/admin/all-jobs'
    | '/admin/announcements'
    | '/admin/deleted-jobs'
    | '/admin/user-management'
    | '/audio-recordings/shared'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/logout'
    | '/_layout/audio-recordings/$id'
    | '/_layout/admin/'
    | '/_layout/analytics/'
    | '/_layout/audio-recordings/'
    | '/_layout/audio-upload/'
    | '/_layout/help/'
    | '/_layout/profile/'
    | '/_layout/prompt-management/'
    | '/_layout/simple-upload/'
    | '/_layout/suggest-template/'
    | '/_layout/unauthorised/'
    | '/_layout/admin/users/$userId'
    | '/_layout/admin/all-jobs/'
    | '/_layout/admin/announcements/'
    | '/_layout/admin/deleted-jobs/'
    | '/_layout/admin/user-management/'
    | '/_layout/audio-recordings/shared/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/unauthorised/': {
      id: '/_layout/unauthorised/'
      path: '/unauthorised'
      fullPath: '/unauthorised/'
      preLoaderRoute: typeof LayoutUnauthorisedIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/suggest-template/': {
      id: '/_layout/suggest-template/'
      path: '/suggest-template'
      fullPath: '/suggest-template/'
      preLoaderRoute: typeof LayoutSuggestTemplateIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/simple-upload/': {
      id: '/_layout/simple-upload/'
      path: '/simple-upload'
      fullPath: '/simple-upload/'
      preLoaderRoute: typeof LayoutSimpleUploadIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/prompt-management/': {
      id: '/_layout/prompt-management/'
      path: '/prompt-management'
      fullPath: '/prompt-management/'
      preLoaderRoute: typeof LayoutPromptManagementIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/help/': {
      id: '/_layout/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof LayoutHelpIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audio-upload/': {
      id: '/_layout/audio-upload/'
      path: '/audio-upload'
      fullPath: '/audio-upload/'
      preLoaderRoute: typeof LayoutAudioUploadIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audio-recordings/': {
      id: '/_layout/audio-recordings/'
      path: '/audio-recordings'
      fullPath: '/audio-recordings/'
      preLoaderRoute: typeof LayoutAudioRecordingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics/': {
      id: '/_layout/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof LayoutAnalyticsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audio-recordings/$id': {
      id: '/_layout/audio-recordings/$id'
      path: '/audio-recordings/$id'
      fullPath: '/audio-recordings/$id'
      preLoaderRoute: typeof LayoutAudioRecordingsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audio-recordings/shared/': {
      id: '/_layout/audio-recordings/shared/'
      path: '/audio-recordings/shared'
      fullPath: '/audio-recordings/shared/'
      preLoaderRoute: typeof LayoutAudioRecordingsSharedIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/user-management/': {
      id: '/_layout/admin/user-management/'
      path: '/admin/user-management'
      fullPath: '/admin/user-management/'
      preLoaderRoute: typeof LayoutAdminUserManagementIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/deleted-jobs/': {
      id: '/_layout/admin/deleted-jobs/'
      path: '/admin/deleted-jobs'
      fullPath: '/admin/deleted-jobs/'
      preLoaderRoute: typeof LayoutAdminDeletedJobsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/announcements/': {
      id: '/_layout/admin/announcements/'
      path: '/admin/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof LayoutAdminAnnouncementsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/all-jobs/': {
      id: '/_layout/admin/all-jobs/'
      path: '/admin/all-jobs'
      fullPath: '/admin/all-jobs/'
      preLoaderRoute: typeof LayoutAdminAllJobsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users/$userId': {
      id: '/_layout/admin/users/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof LayoutAdminUsersUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAudioRecordingsIdRoute: typeof LayoutAudioRecordingsIdRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAnalyticsIndexRoute: typeof LayoutAnalyticsIndexRoute
  LayoutAudioRecordingsIndexRoute: typeof LayoutAudioRecordingsIndexRoute
  LayoutAudioUploadIndexRoute: typeof LayoutAudioUploadIndexRoute
  LayoutHelpIndexRoute: typeof LayoutHelpIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutPromptManagementIndexRoute: typeof LayoutPromptManagementIndexRoute
  LayoutSimpleUploadIndexRoute: typeof LayoutSimpleUploadIndexRoute
  LayoutSuggestTemplateIndexRoute: typeof LayoutSuggestTemplateIndexRoute
  LayoutUnauthorisedIndexRoute: typeof LayoutUnauthorisedIndexRoute
  LayoutAdminUsersUserIdRoute: typeof LayoutAdminUsersUserIdRoute
  LayoutAdminAllJobsIndexRoute: typeof LayoutAdminAllJobsIndexRoute
  LayoutAdminAnnouncementsIndexRoute: typeof LayoutAdminAnnouncementsIndexRoute
  LayoutAdminDeletedJobsIndexRoute: typeof LayoutAdminDeletedJobsIndexRoute
  LayoutAdminUserManagementIndexRoute: typeof LayoutAdminUserManagementIndexRoute
  LayoutAudioRecordingsSharedIndexRoute: typeof LayoutAudioRecordingsSharedIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAudioRecordingsIdRoute: LayoutAudioRecordingsIdRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAnalyticsIndexRoute: LayoutAnalyticsIndexRoute,
  LayoutAudioRecordingsIndexRoute: LayoutAudioRecordingsIndexRoute,
  LayoutAudioUploadIndexRoute: LayoutAudioUploadIndexRoute,
  LayoutHelpIndexRoute: LayoutHelpIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutPromptManagementIndexRoute: LayoutPromptManagementIndexRoute,
  LayoutSimpleUploadIndexRoute: LayoutSimpleUploadIndexRoute,
  LayoutSuggestTemplateIndexRoute: LayoutSuggestTemplateIndexRoute,
  LayoutUnauthorisedIndexRoute: LayoutUnauthorisedIndexRoute,
  LayoutAdminUsersUserIdRoute: LayoutAdminUsersUserIdRoute,
  LayoutAdminAllJobsIndexRoute: LayoutAdminAllJobsIndexRoute,
  LayoutAdminAnnouncementsIndexRoute: LayoutAdminAnnouncementsIndexRoute,
  LayoutAdminDeletedJobsIndexRoute: LayoutAdminDeletedJobsIndexRoute,
  LayoutAdminUserManagementIndexRoute: LayoutAdminUserManagementIndexRoute,
  LayoutAudioRecordingsSharedIndexRoute: LayoutAudioRecordingsSharedIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
